### ISSUE TITLE
Crash when empty keyword

### ISSUE THREAD

**Issue by Namolem** [stipop-development/Stipop_SDK_Android#79]
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method io.stipop.models.SPSticker.<init>, parameter keyword
       at io.stipop.models.SPSticker.<init>(SPSticker.kt:12)
       at io.stipop.models.Sticker.toSPSticker(Sticker.kt:16)
       at io.stipop.adapter.PagingStickerAdapter.onBindViewHolder(PagingStickerAdapter.kt:21)
       at io.stipop.adapter.PagingStickerAdapter.onBindViewHolder(PagingStickerAdapter.kt:9)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7678)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7761)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6582)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6848)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
       at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:584)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1158)
       at androidx.recyclerview.widget.GridLayoutManager.scrollVerticallyBy(GridLayoutManager.java:398)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2009)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2108)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3826)
       at android.view.View.dispatchTouchEvent(View.java:14512)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3180)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:575)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1889)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:880)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:525)
       at android.view.View.dispatchPointerEvent(View.java:14776)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6774)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6540)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5965)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6029)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5988)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6174)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5996)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6231)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5969)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6029)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5988)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5996)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5969)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8980)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8931)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8874)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9136)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9078)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9175)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1452)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1250)
       at android.view.Choreographer.doFrame(Choreographer.java:919)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1437)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:8312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by KimIlKyum** [comment]
Hello, I'm Stipop's mobile sdk developer kyum.

I resolved this issue in 0.9.5-beta.8.

If same crash occurs again, please tell me thanks.
